influxdb:
  host_url: 'localhost'
  port: 8086
  username: '-'
  password: '-'

envoy:
  influx_database: 'energy'
  host_url: 'envoy.local'

darksky:
  influx_database: 'weather'
  latitude: 0
  longitude: 0
  api_key: '-'

pysolar:
  influx_database: 'weather'
  location_tag: '-'
  latitude: 0
  longitude: 0
  panel_count: 0
  panel_area: 0
  panel_altitude: 0
  panel_azimuth: 0
  system_efficiency: 0

ambient:
  influx_database: 'weather'
  mac_address: ''
  api_key: ''
  application_key: ''
  location_tag: ''

ecobee:
  client_id: your ecobee app client id
  influx_database: 'hvac'
  location_tag: ''

mb8600_modem:
  host: 192.168.100.1
  username: '' 
  password: ''
  influx_database: modem