influxdb:
  host_url: '-'
  port: 0
  username: '-'
  password: '-'

envoy:
  influx_database: '-'
  host_url: 'envoy.local'

darksky:
  influx_database: 'weather'
  latitude: 0
  longitude: 0
  api_key: '-'
